---
env:
    name: procgen_coinrun
    distribution_mode: easy
    n_envvecs: 4
    n_envs: &ne 4
    frame_diff: False
    frame_skip: 1
    frame_stack: 1
    np_obs: True
    reward_scale: 1
    reward_clip: 10

model:
    encoder: 
        cnn_name: impala
    actor:
        units_list: [512]
        layer_type: dense
        norm: null
        kernel_initializer: glorot_uniform
        activation: relu
        eval_act_temp: .5
    q:
        units_list: [512]
        layer_type: dense
        norm: null
        kernel_initializer: glorot_uniform
        activation: relu
        duel: False
    temperature:
        temp_type: constant
        value: .01
    reward_kl: False
    additional_rnn_input: False

agent:
    algorithm: &algo seed-mrdqn
    replay_type: &replay seq
    gamma: &gamma .99
    lambda: .95
    batch_size: &bs 64
    precision: 32

    schedule_act_eps: False
    act_eps_type: line
    act_eps: .3
    eval_act_eps: 0
    schedule_act_temp: True
    n_exploit_envs: 8
    min_temp: .5
    max_temp: 10
    
    store_state: False
    burn_in: False
    sample_size: &ss 32
    burn_in_size: &bis 0

    MAX_STEPS: 2.5e7      # maximum env steps
    LOG_PERIOD: 100
    N_UPDATES: 1
    SYNC_PERIOD: 400
    RECORD_PERIOD: 100
    N_EVALUATION: 10
    logger: True

    # distributed algo params
    n_learner_cpus: 1
    n_learner_gpus: .3
    n_workers: 5
    n_worker_cpus: 1
    n_worker_gpus: .1
    run_mode: nsteps
    worker_side_prioritization: False

    # model path: root_dir/model_name/models
    # tensorboard path: root_dir/model_name/logs
    # the following names are just examples; they will be reset in our training process
    root_dir: *algo                         # root path for tensorboard logs
    model_name: *algo

    target_update_period: 1500
    
    soft_target: True

    # arguments for optimizer
    optimizer: adam
    schedule_lr: False
    value_lr: 2.5e-4
    actor_lr: 2.5e-4
    temp_lr: 2.5e-4
    weight_decay: null
    clip_norm: 0
    opt_eps: 1e-7
    prior_lr: 1.e-3
    
    # arguments for PER
    per_alpha: .6
    per_epsilon: 1e-4
    use_is_ratio: &is False

replay:
    replay_type: *replay
    n_envs: *ne
    # arguments for PER
    beta0: .5
    to_update_top_priority: True
    use_is_ratio: *is

    # arguments for sequential replay
    batch_size: *bs
    sample_size: *ss
    burn_in_size: *bis
    min_size: 100
    capacity: 10000
    extra_keys: ['obs', 'action', 'mu', 'mask']
