---
env:
    name: atari_breakout
    sticky_actions: True
    frame_skip: 4
    frame_stack: 4
    life_done: True
    reward_clip: True
    seed: 0

model:
    encoder:
        cnn_name: nature
        out_size: null
    quantile:
        tau_embed_size: 64
        phi_activation: relu
        N: &K 32
    q:
        units_list: [512]
        layer_type: dense
        kernel_initializer: glorot_uniform
        activation: relu

agent:
    algorithm: &algo iqn
    replay_type: &replay uniform
    gamma: &gamma .99
    batch_size: &bs 32
    n_steps: &nsteps 1      # n-step target
    schedule_act_eps: True
    act_eps:
        - [0, 1]
        - [1.e+6, .01]
    eval_act_eps: .001

    MAX_STEPS: 1e8      # maximum env frames
    TRAIN_PERIOD: 16    # #frames = 4 agent step when frame skip = 4
    EVAL_PERIOD: 5e5
    LOG_PERIOD: 5e5
    N_UPDATES: 1
    RECORD: True

    # IQN params
    N: 8                # N in paper, num of quantiles for online quantile network
    N_PRIME: 8          # N' in paper, num of quantiles for target quantile network
    K: *K               # K in paper, num of quantiles for action selection
    KAPPA: 1            # ùúÖ in paper, used as the threshold for the huber loss

    # model path: root_dir/model_name/models
    # tensorboard path: root_dir/model_name/logs
    # the following names are just examples; they will be reset in our training process
    root_dir: *algo                         # root path for tensorboard logs
    model_name: *algo

    target_update_period: 1500
    tbo: False
    
    # arguments for optimizer
    opt_name: adam
    schedule_lr: False
    value_lr: 5e-5
    clip_norm: 40

    # arguments for PER
    per_alpha: .6
    per_epsilon: 1.e-4

replay:
    replay_type: *replay
    # arguments for PER
    beta0: .4
    beta_steps: 1e5
    to_update_top_priority: True

    # arguments for general replay
    n_steps: *nsteps
    gamma: *gamma
    batch_size: *bs
    min_size: 1600
    capacity: 1e5
    has_next_obs: False
