---
env:
    name: procgen_starpilot
    distribution_mode: easy
    n_envs: &ne 4
    frame_stack: 4
    np_obs: True
    reward_scale: 1
    reward_clip: 10

model:
    encoder:
        cnn_name: impala
    fpn:
        N: &N 64
    qe:
        tau_embed_size: 64
        phi_activation: relu
    q:
        units_list: [512]
        layer_type: dense
        norm: null
        kernel_initializer: glorot_uniform
        activation: relu
        duel: False
        stoch_action: True
        tau: &tau 0.003

agent:
    algorithm: &algo apex-fqf
    replay_type: &replay per
    gamma: &gamma .99
    batch_size: &bs 64
    n_steps: &nsteps 3      # n-step target

    MUNCHAUSEN: False   # whether to use munchausen rl target
    probabilistic_regularization: null

    tau: *tau
    alpha: .9
    clip_logpi_min: -1

    schedule_act_eps: True
    act_eps_type: apex
    act_eps: .3
    eval_act_eps: 0
    schedule_act_temp: True
    n_exploit_envs: 8
    min_temp: .5
    max_temp: 10
    eval_act_temp: .5
    
    # timer&interval
    MAX_STEPS: 1e7
    LOG_PERIOD: 100
    N_UPDATES: 1
    SYNC_PERIOD: 400
    RECORD_PERIOD: 100
    N_EVALUATION: 10

    # IQN params
    N: *N               # N in paper, num of quantiles for online quantile network
    KAPPA: 1            # ùúÖ in paper, used as the threshold for the huber loss

    # distributed algo params
    n_learner_cpus: 1
    n_learner_gpus: .3
    n_workers: 5
    n_worker_cpus: 1
    n_worker_gpus: .1
    run_mode: nsteps
    worker_side_prioritization: False
    return_stats: True

    # model path: root_dir/model_name/models
    # tensorboard path: root_dir/model_name/logs
    # the following names are just examples; they will be reset in our training process
    root_dir: *algo                         # root path for tensorboard logs
    model_name: *algo

    target_update_period: 1500
    tbo: False

    # arguments for optimizer
    value_opt: adam
    schedule_lr: False
    value_lr: 2.5e-4
    fpn_opt: rmsprop
    fpn_lr: 2.5e-9
    ent_coef: .001
    clip_norm: 0
    opt_kwargs:
        epsilon: 1.5e-4

    # arguments for PER
    per_alpha: .6
    per_epsilon: 1.e-4
    use_is_ratio: &is False

replay:
    replay_type: *replay
    seqlen: 50
    n_envs: *ne
    # arguments for PER
    beta0: .4
    beta_steps: 2e6
    to_update_top_priority: True
    use_is_ratio: *is

    # arguments for general replay
    n_steps: *nsteps
    max_steps: 3
    gamma: *gamma
    batch_size: *bs
    min_size: 1600
    capacity: 2.5e5
    has_next_obs: True
