---
env:
    name: atari_pong
    sticky_actions: False
    frame_skip: 4
    frame_stack: 4
    life_done: True
    reward_clip: 1
    np_obs: True
    n_envs: 4
    seed: 0

model:
    encoder:
        cnn_name: nature
        out_size: null
    q:
        kernel_initializer: glorot_uniform
        units_list: [512]
        activation: relu
        layer_type: dense
    quantile:
        tau_embed_size: 64
        phi_activation: relu
        K: &K 32

agent:
    algorithm: &algo apex-iqn
    replay_type: &replay per
    gamma: &gamma 0.99
    batch_size: &bs 32
    n_steps: &nsteps 3      # n-step target
    precision: &prec 32

    schedule_act_eps: True
    act_eps_type: apex
    act_eps: .4
    eval_act_eps: .001

    tau: .003
    alpha: .9
    clip_logpi_min: -1

    # timer&interval
    MAX_STEPS: 1e9
    LOG_PERIOD: &log 100
    N_UPDATES: *log
    SYNC_PERIOD: 1000

    # distributed algo params
    n_learner_cpus: 1
    n_learner_gpus: .3
    n_workers: 5
    n_worker_cpus: 1
    n_worker_gpus: .1
    run_mode: nsteps
    worker_side_prioritization: False
    # SYNC_PERIOD: 50
    has_evaluator: True
    N_EVALUATION: 1
    RECORD_PERIOD: 10

    # IQN params
    N: 32                # N in paper, num of quantiles for online quantile network
    N_PRIME: 32          # N' in paper, num of quantiles for target quantile network
    K: *K               # K in paper, num of quantiles for action selection
    KAPPA: 1            # ùúÖ in paper, used as the threshold for the huber loss

    # model path: root_dir/model_name/models
    # tensorboard path: root_dir/model_name/logs
    # the following names are just examples; they will be reset in our training process
    root_dir: *algo                         # root path for tensorboard logs
    model_name: *algo

    target_update_period: 1500
    tbo: False

    # arguments for optimizer
    opt_name: adam
    schedule_lr: False
    lr: 1e-4
    clip_norm: 0
    opt_kwargs:
        epsilon: 3.125e-4

    # arguments for PER
    per_alpha: .5
    per_epsilon: 1.e-4

replay:
    replay_type: *replay
    seqlen: 100
    precision: 32
    # arguments for PER
    beta0: 0.4
    to_update_top_priority: False

    # arguments for general replay
    n_steps: *nsteps
    gamma: *gamma
    batch_size: *bs
    min_size: 5e4
    capacity: 1e5
    has_next_obs: True
