---
env:
    name: procgen_starpilot
    distribution_mode: easy
    n_envs: &ne 4
    frame_stack: 1
    np_obs: True
    reward_scale: 1
    reward_clip: 10

model:
    encoder: 
        cnn_name: impala
    # rnn:
    #     units: 512
    q:
        units_list: [512]
        layer_type: dense
        norm: null
        kernel_initializer: glorot_uniform
        activation: relu
        duel: False
        stoch_action: True
        tau: &tau 0.01

agent:
    algorithm: &algo apex-mrdqn
    replay_type: &replay seq
    gamma: .99
    lambda: .95
    batch_size: &bs 32
    precision: 16

    MUNCHAUSEN: False   # whether to use munchausen rl target
    probabilistic_regularization: null

    tau: *tau
    alpha: .9
    clip_logpi_min: -1

    schedule_act_eps: True
    act_eps_type: apex
    act_eps: .3
    eval_act_eps: 0
    schedule_act_temp: False
    n_exploit_envs: 8
    min_temp: .5
    max_temp: 10
    eval_act_temp: .5

    store_state: False
    burn_in: False
    sample_size: &ss 16
    burn_in_size: &bis 0

    MAX_STEPS: 2.5e7
    LOG_PERIOD: 100
    N_UPDATES: 1
    SYNC_PERIOD: 400
    RECORD_PERIOD: 100
    N_EVALUATION: 10

    # distributed algo params
    n_learner_cpus: 1
    n_learner_gpus: .3
    n_workers: 4
    n_worker_cpus: 1
    n_worker_gpus: .1
    run_mode: nsteps
    worker_side_prioritization: False
    return_stats: False

    # model path: root_dir/model_name/models
    # tensorboard path: root_dir/model_name/logs
    # the following names are just examples; they will be reset in our training process
    root_dir: *algo                         # root path for tensorboard logs
    model_name: *algo

    loss_type: mse
    target_update_period: 1500
    tbo: False
    
    loo_c: 1.
    v_pi_coef: 1.
    reinforce_coef: 1.
    tau: *tau
    # arguments for optimizer
    optimizer: adam
    schedule_lr: False
    actor_lr: 2.5e-4
    value_lr: 2.5e-4
    opt_eps: 1e-7

    # arguments for PER
    per_alpha: .9
    per_eta: .9
    per_epsilon: 1e-4
    use_is_ratio: &is False

replay:
    replay_type: *replay
    n_envs: *ne
    # arguments for PER
    beta0: .5
    to_update_top_priority: True
    use_is_ratio: *is

    # arguments for sequential replay
    batch_size: *bs
    sample_size: *ss
    burn_in_size: *bis
    min_size: 100
    capacity: 30000
    state_keys: ['h', 'c']
    extra_keys: ['obs', 'action', 'mu', 'mask']
