---
env:
    name: procgen_coinrun
    distribution_mode: easy
    n_envs: &ne 4
    frame_stack: 4
    np_obs: True
    reward_scale: .1

model:
    encoder: 
        cnn_name: impala
    quantile:
        tau_embed_size: 64
        phi_activation: relu
        K: &K 64
    q:
        units_list: [512]
        layer_type: dense
        norm: null
        kernel_initializer: glorot_uniform
        activation: relu
        duel: False
        stoch_action: True
        tau: &tau 0.01
    additional_rnn_input: False

agent:
    algorithm: &algo apex-mriqn
    replay_type: &replay seq
    gamma: .99
    lambda: .95
    batch_size: &bs 32

    MUNCHAUSEN: False   # whether to use munchausen rl target
    probabilistic_regularization: entropy

    tau: *tau
    alpha: .9
    clip_logpi_min: -1

    schedule_act_eps: True
    act_eps_type: apex
    act_eps: .3
    eval_act_eps: 0
    schedule_act_temp: True
    n_exploit_envs: 8
    min_temp: .5
    max_temp: 10
    eval_act_temp: .5

    store_state: False
    burn_in: False
    sample_size: &ss 16
    burn_in_size: &bis 0

    MAX_STEPS: 1.5e7
    LOG_PERIOD: 100
    N_UPDATES: 1
    SYNC_PERIOD: 400
    RECORD_PERIOD: 100
    N_EVALUATION: 10
    logger: True

    # IQN params
    N: 64                # N in paper, num of quantiles for online quantile network
    N_PRIME: 64          # N' in paper, num of quantiles for target quantile network
    K: *K               # K in paper, num of quantiles for action selection
    KAPPA: 1            # ùúÖ in paper, used as the threshold for the huber loss

    # distributed algo params
    n_learner_cpus: 1
    n_learner_gpus: .3
    n_workers: 5
    n_worker_cpus: 1
    n_worker_gpus: .1
    run_mode: nsteps
    worker_side_prioritization: False
    return_stats: False

    # model path: root_dir/model_name/models
    # tensorboard path: root_dir/model_name/logs
    # the following names are just examples; they will be reset in our training process
    root_dir: *algo                         # root path for tensorboard logs
    model_name: *algo

    target_update_period: 1500

    # arguments for optimizer
    opt_name: adam
    schedule_lr: False
    lr: 2.5e-4
    opt_kwargs:
        epsilon: 1.e-7

    # arguments for PER
    per_alpha: .9
    per_eta: .9
    per_epsilon: 1.e-4
    use_is_ratio: &is False

replay:
    replay_type: *replay
    n_envs: *ne
    # arguments for PER
    beta0: .5
    to_update_top_priority: True
    use_is_ratio: *is

    # arguments for sequential replay
    batch_size: *bs
    sample_size: *ss
    burn_in_size: *bis
    min_size: 100
    capacity: 10000
    state_keys: ['h', 'c']
    extra_keys: ['obs', 'action', 'mu', 'mask']
