---
env:
    name: procgen_coinrun
    distribution_mode: easy
    frame_skip: 1
    n_envs: &ne 64
    frame_stack: 1
    np_obs: True
    reward_scale: 1
    reward_clip: 10

model:
    encoder:
        cnn_name: impala
    fpn:
        N: &N 64
    qe:
        tau_embed_size: 64
        phi_activation: relu
    q:
        units_list: [512]
        layer_type: dense
        norm: null
        kernel_initializer: glorot_uniform
        activation: relu
        duel: False

agent:
    algorithm: &algo fqf
    replay_type: &replay per
    gamma: &gamma 0.99
    batch_size: &bs 64
    n_steps: &nsteps 3      # n-step target
    schedule_act_eps: True
    act_eps_type: apex
    act_eps: .3
    eval_act_eps: 0

    MAX_STEPS: 2.5e7
    TRAIN_PERIOD: 1
    EVAL_PERIOD: 2.5e5
    LOG_PERIOD: 2.5e5
    N_UPDATES: 1
    RECORD: True
    N_EVAL_EPISODES: 200

    return_stats: True
    logger: True

    # IQN params
    N: *N               # N in paper, num of quantiles for online quantile network
    KAPPA: 1            # ùúÖ in paper, used as the threshold for the huber loss

    # model path: root_dir/model_name/models
    # tensorboard path: root_dir/model_name/logs
    # the following names are just examples; they will be reset in our training process
    root_dir: *algo                         # root path for tensorboard logs
    model_name: *algo

    target_update_period: 1500  # trainning step
    tbo: False                              # transformed Bellman Operator
    
    # arguments for optimizer
    value_opt: adam
    schedule_lr: False
    value_lr: 2.5e-4
    fpn_opt: rmsprop
    fpn_lr: 2.5e-9
    ent_coef: .001
    clip_norm: 10
    opt_eps: 3.125e-4

    # arguments for PER
    per_alpha: .6
    per_epsilon: 1e-4
    

replay:
    replay_type: *replay
    seqlen: 10
    n_envs: *ne
    # arguments for PER
    beta0: .4
    beta_steps: 1e6
    to_update_top_priority: True
    use_is_ratio: True

    # arguments for general replay
    n_steps: *nsteps
    max_steps: 3
    gamma: *gamma
    batch_size: *bs
    min_size: 1600
    capacity: 2.5e5
    has_next_obs: True
